pool: vistara-agent

stages:

- stage: terraform_init_and_validate
  displayName: TerraformInitAndValidate

  jobs:
  - job: init_validate
    displayName: TerraformInitAndValidate

    steps:
    - task: TerraformTask@5
      displayName: TerraformInit
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'YML-VIRAT-TEST'
        backendAzureRmResourceGroupName: 'rg-virat'
        backendAzureRmStorageAccountName: 'storagevirat'
        backendAzureRmContainerName: 'container2'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: TerraformValidate
      inputs:
        provider: 'azurerm'
        command: 'validate'


- stage: terraform_plan
  displayName: TerraformPlan

  jobs:
  - job: terraform_plan
    displayName: TerraformPlan

    steps:
    - task: TerraformTask@5
      displayName: TerraformInit
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'YML-VIRAT-TEST'
        backendAzureRmResourceGroupName: 'rg-virat'
        backendAzureRmStorageAccountName: 'storagevirat'
        backendAzureRmContainerName: 'container2'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: TerraformPlan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'YML-VIRAT-TEST'


- stage: terraform_apply
  displayName: TerraformApply

  jobs:
  - job: terraform_apply
    displayName: TerraformApply

    steps:
    - task: TerraformTask@5
      displayName: TerraformInit
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'YML-VIRAT-TEST'
        backendAzureRmResourceGroupName: 'rg-virat'
        backendAzureRmStorageAccountName: 'storagevirat'
        backendAzureRmContainerName: 'container2'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: TerraformApply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'YML-VIRAT-TEST'

