
pool: vistara-agent

stages:

- stage: terraform_init_and_validate
  displayName: TerraformInitAndValidate

  jobs:
  - job: init_validate
    displayName: TerraformInitAndValidate

    steps:
    - script: terraform init
      displayName: TerraformInit

    - script: terraform validate
      displayName: TerraformValidate


- stage: terraform_plan
  displayName: TerraformPlan

  jobs:
  - job: terraform_plan
    displayName: TerraformPlan

    steps:
    - script: terraform init
      displayName: TerraformInit

    - script: terraform plan
      displayName: TerraformPlan


- stage: terraform_apply
  displayName: TerraformApply

  jobs:
  - job: terraform_apply
    displayName: TerraformApply

    steps:
    - script: terraform init
      displayName: TerraformInit

    - script: terraform apply -auto-approve
      displayName: TerraformApply

